name: Pull Request Action
on:
  push:
    branches:
      - test-*
      
jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Check if PR exists
        id: check
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          prs=$(gh pr list \
              --repo "$GITHUB_REPOSITORY" \
              --json baseRefName,headRefName \
              --jq '
                  map(select(.baseRefName == "main" and .headRefName == "${{ github.ref_name }}"))
                  | length
              ')
          if ((prs > 0)); then
              echo "skip=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Split string
        # if: '!steps.check.outputs.skip'
        env:
          BRANCH: ${{ github.ref_name }}
          Issue_ID: ${ ${{ github.ref_name }}% ${{ github.ref_name }}#*-[0-9]+-}
          Issue_Title: ${ ${{github.ref_name }}#*-[0-9]+-}
        id: split
        run:
          # echo "${ BRANCH% ${BRANCH#*-[0-9]+-}}"
          # echo "${ BRANCH#*-[0-9]+-}"
          echo "${BRANCH#*-[1-9][0-9]?-}"

      - name: Create pull request
        if: '!steps.check.outputs.skip'
        uses: actions/github-script@v6
        with:
          script: |
            const { repo, owner } = context.repo;
            const result = await github.rest.pulls.create({
              title: [
                '[${{ env.Issue_ID }}]',
                '${{ env.Issue_Title }}'
              ].join(' '),
              owner,
              repo,
              head: "${{ github.ref_name }}",
              base: "main",
              body: [
                'This PR is auto-generated by',
                '[actions/github-script](https://github.com/actions/github-script).'
              ].join('\n')
            });
        